Entity/Crossword.php
<?php

namespace SC\CrosswordBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use \DateTime;
use SC\CrosswordBundle\Word;

/**
 * Crossword
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Crossword
{
    const MAX_WIDTH = 25;
    const MAX_HEIGHT = 40;


    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var integer
     *
     * @ORM\Column(name="width", type="integer")
     */
    private $width;

    /**
     * @var integer
     *
     * @ORM\Column(name="height", type="integer")
     */
    private $height;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="user_id", type="string", length=255)
     */
    private $user = 1;

    /**
     * @var Letter[]
     *
     * @ORM\OneToMany(targetEntity="Letter", mappedBy="crossword")
     **/
    private $letters;

    /**
     * @var Question[]
     *
     * @ORM\OneToMany(targetEntity="Question", mappedBy="crossword")
     **/
    private $questions;

    /**
     * @var array
     */
    private $matrix = [];

    /**
     * @var array
     */
    private $words = [];

    /**
     * @var array
     */
    private $wordsCoord;

    public function __construct()
    {
        $this->createdAt = new DateTime();
        $this->letters   = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Crossword
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set width
     *
     * @param integer $width
     * @return Crossword
     */
    public function setWidth($width)
    {
        $this->width = $width <= self::MAX_WIDTH ? $width : self::MAX_WIDTH;

        return $this;
    }

    /**
     * Get width
     *
     * @return integer 
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Set height
     *
     * @param integer $height
     * @return Crossword
     */
    public function setHeight($height)
    {
        $this->height = $height <= self::MAX_HEIGHT ? $height : self::MAX_HEIGHT;

        return $this;
    }

    /**
     * Get height
     *
     * @return integer 
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Crossword
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set user
     *
     * @param string $user
     * @return Crossword
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return string 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @return Letter[]
     */
    public function getLetters()
    {
        return $this->letters;
    }

    /**
     * @return array
     */
    public function getMatrix()
    {
        if (count($this->matrix) == 0) {
            $letters = $this->getLetters();
            foreach ($letters as $letter) {
                $this->matrix[$letter->getX()][$letter->getY()] = $letter->getLetter();
            }
        }

        return $this->matrix;
    }

    /**
     * @param $x
     * @param $y
     *
     * @return string
     */
    public function getLetterByCoord($x, $y)
    {
        $matrix = $this->getMatrix();

        return isset($matrix[$x][$y]) ? $matrix[$x][$y] : "";
    }

    /**
     * @param $x
     * @param $y
     *
     * @return string
     */
    public function getHasLetterByCoord($x, $y)
    {
        return (bool) strlen($this->getLetterByCoord($x, $y));
    }

    /**
     * @return Word[]
     */
    public function getWords()
    {
        /** @var $word Word */
        if (count($this->words)) {
            return $this->words;
        }

        $this->words = [];

        $words  = [];
        $matrix =  $this->getMatrix();

        $invert = [];
        foreach ($matrix as $x => $row) {
            foreach ($row as $y => $char) {
                $invert[$y][$x] = $char;
            }
        }

        $words = array_merge($words, $this->detectWords($matrix, Word::VERTICAL));
        $words = array_merge($words, $this->detectWords($invert, Word::HORIZONTAL));

        $orderedWords = [];
        foreach ($words as $word) {
            $orderedWords[$word->getOrder()][] = $word;
        }
        ksort($orderedWords);

        $numberedWords = [];
        foreach ($orderedWords as $order => $wordsGroup) {
            foreach ($wordsGroup as $key => $word) {
                $numberedWords[] = $word;
            }
        }

        foreach (array_values($numberedWords) as $number => $word) {
            $word->setNumber($number + 1);
            $this->words[] = $word;
        }

        foreach ($this->words as $word) {
            $this->wordsCoord[$word->getStartX()][$word->getStartY()][] = $word;
        }

        return $this->words;
    }

    /**
     * @param $x
     * @param $y
     *
     * @return bool
     */
    public function getIsWordStart($x, $y)
    {
        $this->getWords();

        return (isset($this->wordsCoord[$x][$y]) && count($this->wordsCoord[$x][$y]) > 0);
    }

    /**
     * @param $x
     * @param $y
     *
     * @return array|null
     */
    public function getWordNumbers($x, $y)
    {
        $this->getWords();

        if (!isset($this->wordsCoord[$x][$y])) {
            return null;
        }

        $numbers = [];
        foreach ($this->wordsCoord[$x][$y] as $word) {
            $numbers[] = $word->getNumber();
        }

        return $numbers;
    }

    /**
     * @param $number
     *
     * @return Word
     */
    public function getWordByNumber($number)
    {
        foreach ($this->getWords() as $word) {
            if ($word->getNumber() == $number) {
                return $word;
            }
        }

        return null;
    }

    /**
     * @param $x
     * @param $y
     *
     * @return array|null
     */
    public function getWordCount()
    {
       return count($this->getWords());
    }

    /**
     * @param $matrix
     * @param $type
     *
     * @return Word[]
     */
    private function detectWords($matrix, $type)
    {
        /** @var Word $word */
        $words = [];

        foreach ($matrix as $x => $row) {
            ksort($row);
            $previousY = 0;
            unset($word);

            $counter = 1;
            foreach ($row as $y => $char) {
                $delta = $y - $previousY;
                if ($delta > 1 || ($y == 1 && $delta == 1)) {
                    if (isset($word) and $word->getLength() > 1) {
                        $words[] = $word;
                    }
                    $word = new Word($x, $y, $char);
                    $word->setType($type);
                } elseif ($delta == 1 && isset($word)) {
                    $word->addLetter($x, $y, $char);
                }

                if (isset($word)) {
                    $len = $word->getLength();
                }
                if (isset($word) and $word->getLength() > 1 && count($row) == $counter) {
                    $words[] = $word;
                }

                $previousY = $y;
                $counter++;
            }
        }

        return $words;
    }

    /**
     * @return Question[]
     */
    public function getQuestions()
    {
        return $this->questions;
    }

    /**
     * @return Question[]
     */
    public function getVerticalQuestions()
    {
        $words     = $this->getWords();
        $questions = $this->getQuestions();

        $selectedQuestions  = [];
        $questionsNumerated = [];

        foreach ($questions as $question) {
            $questionsNumerated[$question->getNumber()] = $question;
        }

        foreach ($words as $word) {
            if ($word->isVertical() && isset($questionsNumerated[$word->getNumber()])) {
                $selectedQuestions[] = $questionsNumerated[$word->getNumber()];
            }
        }

        return $selectedQuestions;
    }

    /**
     * @return Question[]
     */
    public function getHorizontalQuestions()
    {
        $words     = $this->getWords();
        $questions = $this->getQuestions();

        $selectedQuestions  = [];
        $questionsNumerated = [];

        foreach ($questions as $question) {
            $questionsNumerated[$question->getNumber()] = $question;
        }

        foreach ($words as $word) {
            if ($word->isHorizontal() && isset($questionsNumerated[$word->getNumber()])) {
                $selectedQuestions[] = $questionsNumerated[$word->getNumber()];
            }
        }

        return $selectedQuestions;
    }

    /**
     * @param $number
     *
     * @return string
     */
    public function getQuestionByNumber($number)
    {
        foreach ($this->getQuestions() as $question) {
            if ($question->getNumber() == $number) {
                return $question->getText();
            }
        }

        return "";
    }
}

Resources/views/Admin/create.html.twig
{% extends '::layout.html.twig' %}

{% block title %}Админка | Список пользователей{% endblock %}
{% block body %}
  <div class="row">
    <div class="span6">
    </div>
    <div style="text-align: right;" class="span6"><a href="{{ path('sc_users_new') }}" class="btn btn-primary">Создать нового пользователя</a></div>
  </div>


  <table class="table table-bordered">
    <caption>Пользователи</caption>
    <thead>
    <tr>
      <th>id</th>
      <th>Имя</th>
      <th>Логин</th>
      <th>Дата создания</th>
      <th>Роль</th>
    </tr>
    </thead>
    <tbody>
    {% for user in pagination %}
      <tr>
        <td><a href="{{ path('sc_users_edit', {'userId' :user.id}) }}">{{ user.id }}</a></td>
        <td><a href="{{ path('sc_users_edit', {'userId' :user.id}) }}">{{ user.screenName }}</a></td>
        <td>{{ user.username }}</td>
        <td>{{ user.createdAt|date('d M Y h:i') }}</td>
        <td>{{ user.roles[0].screenName }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <br />
  {{ knp_pagination_render(pagination) }}
{% endblock %}

Resources/views/Admin/edit.html.twig
{% extends '::layout.html.twig' %}

{% block title %}Админка | Редактирование кроссворда{% endblock %}
{% block body %}

  <style>
    .letter-cell {
      padding: 0;
      border: 1px solid #ccc;
    }
    .letter-cell .letter {
      width: 20px;
      height: 20px;
      box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.15);
      outline: none;
      padding: 5px;
      font-size: 18px;
      text-align: center;
      background: #fff;
    }
    .letter-cell-selected .letter {
      background: #eee;
    }
    .coord-num {
      font-size: 11px;
      color: #aaa;
      text-align: center;
      padding-right: 7px;
    }
    .btn-questions {
      margin: 20px 0 40px 20px;
    }
  </style>

  <script>
    $(function () {
      $(".letter-cell").hover(
          function() {
            var x = $(this).data('x');
            var y = $(this).data('y');

            $(".coord-x-" + x).addClass('letter-cell-selected');
            $(".coord-y-" + y).addClass('letter-cell-selected');
          },
          function() {
            var x = $(this).data('x');
            var y = $(this).data('y');

            $(".coord-x-" + x).removeClass('letter-cell-selected');
            $(".coord-y-" + y).removeClass('letter-cell-selected');
          }
      );

      $('.letter').keyup(function(e) {
        saveLetter(e);
        swithPosition(e);
        checkCharCount(e);
      });
      $('.letter').keydown(function(e) {
        swithPosition(e);
        checkCharCount(e);
      });

      function swithPosition(e) {
        var x = $("#" + e.target.id).parent().data('x');
        var y = $("#" + e.target.id).parent().data('y');

        // left
        if (e.which == 37) {
          var newX = x > 1 ? x - 1 : 1;
          $(".letter-" + newX + "-" + y).get(0).focus();
          e.preventDefault();
        }
      }

      function saveLetter(e)
      {
        var letterField = $("#" + e.target.id);
        var data = {
          letter: letterField.text(),
          x:      letterField.parent().data('x'),
          y:      letterField.parent().data('y')
        };

        $.ajax({
          type: "POST",
          url: '{{ path('sc_crossword_admin_add_letter_ajax', {id: crossword.id}) }}',
          data: data,
          dataType: "json",
          success: function(response) {
            if (response.success) {
              $("#crossword-name").val("");
              $("#crossword-width").val("");
              $("#crossword-height").val("");
              $('#create-crossword').modal('hide');
              $(".crossword-list").prepend(response.row);
            } else {

            }
            self.removeClass('disabled');
          },
          error: function(response) {
            self.removeClass('disabled');
          }
        });
      }

      function checkCharCount(e) {
        if (e.which != 8 && e.which != 9 && $("#" + e.target.id).text().length >= 1) {
          e.preventDefault();
        }
      }
    });
  </script>

  <ul class="breadcrumb">
    <li><a href="/">Главная</a> <span class="divider">/</span></li>
    <li><a href="{{ path('sc_crossword_admin_list') }}">Кроссворды</a> <span class="divider">/</span></li>
    <li class="active">{{ crossword.name }}</li>
  </ul>

  <table>
    <tr>
      <td></td>
      {% for x in 1..crossword.width %}
        <td class="coord-num">
          {{ x }}
        </td>
      {% endfor %}
    </tr>
    {% for y in 1..crossword.height %}
      <tr>
        <td class="coord-num">
          {{ y }}
        </td>
        {% for x in 1..crossword.width %}
        <td class="letter-cell coord-x-{{ x }} coord-y-{{ y }}" data-x="{{ x }}" data-y="{{ y }}">
          <div class="letter" id="letter-{{ x }}-{{ y }}" contenteditable="true" maxlength="1">{{ crossword.letterByCoord(x, y) }}</div>
        </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </table>

  <a href="{{ path('sc_crossword_admin_questions', {id: crossword.id}) }}" class="btn btn-primary btn-questions">Перейти к вопросам</a>

{% endblock %}

Resources/views/Admin/list.html.twig
{% extends '::layout.html.twig' %}

{% block title %}Админка | Список кроссвордов{% endblock %}
{% block body %}
  <script>
    $(function(){
      $("#create-crossword-btn").click(function(){
        $('#create-crossword').modal('toggle');
      });

      $("#create-crossword-btn-save").click(function(){
        self = $(this);
        self.addClass('disabled');

        var data = {
          name:   $("#crossword-name").val(),
          width:  $("#crossword-width").val(),
          height: $("#crossword-height").val()
        };

        $.ajax({
          type: "POST",
          url: '{{ path('sc_crossword_admin_create_ajax') }}',
          data: data,
          dataType: "json",
          success: function(response) {
            if (response.success) {
              $("#crossword-name").val("");
              $("#crossword-width").val("");
              $("#crossword-height").val("");
              $('#create-crossword').modal('hide');
              $(".crossword-list").prepend(response.row);
            } else {

            }
            self.removeClass('disabled');
          },
          error: function(response) {
            self.removeClass('disabled');
          }
        });
      });

    });
  </script>

  <div class="row">
    <div class="span6">
    </div>
    <div style="text-align: right;" class="span6">
      <a href="#create-crossword" id="create-crossword-btn" role="button" class="btn btn-primary" -data-toggle="modal">Создать новый кроссворд</a>
    </div>

    <!-- Modal -->
    <div id="create-crossword" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Создание нового кроссворда</h3>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
          <div class="control-group">
            <label class="control-label" for="crossword-name">Название</label>
            <div class="controls">
              <input type="text" id="crossword-name" placeholder="Название">
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="crossword-width">Ширина</label>
            <div class="controls">
              <input type="text" id="crossword-width" placeholder="ширина в клетках < {{ constant('SC\\CrosswordBundle\\Entity\\Crossword::MAX_WIDTH') }}">
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="crossword-height">Высота</label>
            <div class="controls">
              <input type="text" id="crossword-height" placeholder="высота в клетках < {{ constant('SC\\CrosswordBundle\\Entity\\Crossword::MAX_HEIGHT') }}">
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Закрыть</button>
        <button class="btn btn-primary" id="create-crossword-btn-save">Создать</button>
      </div>
    </div>
  </div>




  <table class="table table-bordered">
    <caption>Кроссворды</caption>
    <thead>
    <tr>
      <th>id</th>
      <th>название</th>
      <th>дата создания</th>
    </tr>
    </thead>
    <tbody class="crossword-list">
    {% for crossword in pagination %}
      <tr>
        <td><a href="{{ path('sc_crossword_admin_edit', {'id' : crossword.id}) }}">{{ crossword.id }}</a></td>
        <td><a href="{{ path('sc_crossword_admin_edit', {'id' : crossword.id}) }}">{{ crossword.name }}</a></td>
        <td>{{ crossword.createdAt|date('d M Y h:i') }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <br />
  {{ knp_pagination_render(pagination) }}
{% endblock %}

Resources/views/Admin/questions.html.twig
{% extends '::layout.html.twig' %}

{% block title %}Админка | Редактирование кроссворда{% endblock %}
{% block body %}

  <style>
    .letter-cell {
      padding: 0;
      border: 1px solid #ccc;
    }
    .letter-cell .letter {
      width: 20px;
      height: 20px;
      outline: none;
      padding: 5px;
      font-size: 18px;
      text-align: center;
      background: #fff;
      position: relative;
    }
    .letter-cell-selected .letter {
      background: #eee;
    }
    .letter-cell-disabled  .letter {
      background: #B1AC9E;
    }
    .letter-cell-disabled {
      border-color: #878378;
    }
    .coord-num {
      font-size: 11px;
      color: #aaa;
      text-align: center;
      padding-right: 7px;
    }
    .btn-questions {
      margin: 20px 0 40px 20px;
    }
    .word-num {
      position: absolute;
      font-size: 11px;
      border-radius: 10px;
      padding: 3px;
      /*border: 1px solid #cab78f;*/
      top: -11px;
      left: -11px;
      width: 14px;
      height: 14px;
      background: #333;
      line-height: 15px;
      color: #fff;
    }
    .questions {
      margin-top: 20px ;
    }
    .btn-questions-save {
      margin: 10px 0 30px 30px;
    }
    .btn-crossword-edit {
      margin-bottom: 20px;
    }
  </style>

  <script>
    $(function () {

      $(".btn-questions-save").click(function(){
        self = $(this);
        var questions = [];
        $(".question").each(function() {
          var question = {
            text:   $(this).val(),
            number: $(this).data('number')
          };
          questions.push(question);
        });

        self.addClass('disabled');

        $.ajax({
          type: "POST",
          url: '{{ path('sc_crossword_admin_questions_save_ajax', {id: crossword.id}) }}',
          data: {questions: questions},
          dataType: "json",
          success: function(response) {
            if (response.success) {
            } else {

            }
            self.removeClass('disabled');
          },
          error: function(response) {
            self.removeClass('disabled');
          }
        });
      });

    });
  </script>


  <ul class="breadcrumb">
    <li><a href="/">Главная</a> <span class="divider">/</span></li>
    <li><a href="{{ path('sc_crossword_admin_list') }}">Кроссворды</a> <span class="divider">/</span></li>
    <li class="active">{{ crossword.name }}</li>
  </ul>

  <a href="{{ path("sc_crossword_admin_edit", {id: crossword.id}) }}" class="btn btn-default btn-small btn-crossword-edit">Вернуться к заполнению слов</a>

  <table>
    <tr>
      <td></td>
      {% for x in 1..crossword.width %}
        <td class="coord-num">
          {{ x }}
        </td>
      {% endfor %}
    </tr>
    {% for y in 1..crossword.height %}
      <tr>
        <td class="coord-num">
          {{ y }}
        </td>
        {% for x in 1..crossword.width %}
          <td class="letter-cell {% if not crossword.hasLetterByCoord(x, y) %} letter-cell-disabled {% endif %} coord-x-{{ x }} coord-y-{{ y }}" data-x="{{ x }}" data-y="{{ y }}">
            <div class="letter" id="letter-{{ x }}-{{ y }}" maxlength="1">
              {% if crossword.isWordStart(x, y) %}
                <div class="word-num">{% for number in crossword.wordNumbers(x, y) %}{{ number }}{% if not loop.last %},{% endif %}{% endfor %}</div>
              {% endif %}
              {{ crossword.letterByCoord(x, y) }}
            </div>
          </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </table>

  <div class="questions">
    {% for number in 1..crossword.wordCount %}
    <div class="row-fluid">
      <div class="span7">
        <div style="float: left; width: 30px;">{{ number }}</div>
        <textarea class="span11 question" data-number="{{ number }}" rows="2">{{ crossword.questionByNumber(number) }}</textarea>
      </div>
    </div>
    {% endfor %}
  </div>

  <button class="btn btn-primary btn-questions-save">Сохранить</button>

{% endblock %}

Resources/views/Admin/row.html.twig
<tr>
  <td><a href="{{ path('sc_crossword_admin_edit', {'id' : crossword.id}) }}">{{ crossword.id }}</a></td>
  <td><a href="{{ path('sc_crossword_admin_edit', {'id' : crossword.id}) }}">{{ crossword.name }}</a></td>
  <td>{{ crossword.createdAt|date('d M Y h:i') }}</td>
</tr>