Entity/Crossword.php
<?php

namespace SC\CrosswordBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use \DateTime;
use SC\CrosswordBundle\Word;

/**
 * Crossword
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Crossword
{
    const MAX_WIDTH = 25;
    const MAX_HEIGHT = 40;


    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var integer
     *
     * @ORM\Column(name="width", type="integer")
     */
    private $width;

    /**
     * @var integer
     *
     * @ORM\Column(name="height", type="integer")
     */
    private $height;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="user_id", type="string", length=255)
     */
    private $user = 1;

    /**
     * @var Letter[]
     *
     * @ORM\OneToMany(targetEntity="Letter", mappedBy="crossword")
     **/
    private $letters;

    /**
     * @var Question[]
     *
     * @ORM\OneToMany(targetEntity="Question", mappedBy="crossword")
     **/
    private $questions;

    /**
     * @var array
     */
    private $matrix = [];

    /**
     * @var array
     */
    private $words = [];

    /**
     * @var array
     */
    private $wordsCoord;

    public function __construct()
    {
        $this->createdAt = new DateTime();
        $this->letters   = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Crossword
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set width
     *
     * @param integer $width
     * @return Crossword
     */
    public function setWidth($width)
    {
        $this->width = $width <= self::MAX_WIDTH ? $width : self::MAX_WIDTH;

        return $this;
    }

    /**
     * Get width
     *
     * @return integer 
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Set height
     *
     * @param integer $height
     * @return Crossword
     */
    public function setHeight($height)
    {
        $this->height = $height <= self::MAX_HEIGHT ? $height : self::MAX_HEIGHT;

        return $this;
    }

    /**
     * Get height
     *
     * @return integer 
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Crossword
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set user
     *
     * @param string $user
     * @return Crossword
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return string 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @return Letter[]
     */
    public function getLetters()
    {
        return $this->letters;
    }

    /**
     * @return array
     */
    public function getMatrix()
    {
        if (count($this->matrix) == 0) {
            $letters = $this->getLetters();
            foreach ($letters as $letter) {
                $this->matrix[$letter->getX()][$letter->getY()] = $letter->getLetter();
            }
        }

        return $this->matrix;
    }

    /**
     * @param $x
     * @param $y
     *
     * @return string
     */
    public function getLetterByCoord($x, $y)
    {
        $matrix = $this->getMatrix();

        return isset($matrix[$x][$y]) ? $matrix[$x][$y] : "";
    }

    /**
     * @param $x
     * @param $y
     *
     * @return string
     */
    public function getHasLetterByCoord($x, $y)
    {
        return (bool) strlen($this->getLetterByCoord($x, $y));
    }

    /**
     * @return Word[]
     */
    public function getWords()
    {
        /** @var $word Word */
        if (count($this->words)) {
            return $this->words;
        }

        $this->words = [];

        $words  = [];
        $matrix =  $this->getMatrix();

        $invert = [];
        foreach ($matrix as $x => $row) {
            foreach ($row as $y => $char) {
                $invert[$y][$x] = $char;
            }
        }

        $words = array_merge($words, $this->detectWords($matrix, Word::VERTICAL));
        $words = array_merge($words, $this->detectWords($invert, Word::HORIZONTAL));

        $orderedWords = [];
        foreach ($words as $word) {
            $orderedWords[$word->getOrder()][] = $word;
        }
        ksort($orderedWords);

        $numberedWords = [];
        foreach ($orderedWords as $order => $wordsGroup) {
            foreach ($wordsGroup as $key => $word) {
                $numberedWords[] = $word;
            }
        }

        foreach (array_values($numberedWords) as $number => $word) {
            $word->setNumber($number + 1);
            $this->words[] = $word;
        }

        foreach ($this->words as $word) {
            $this->wordsCoord[$word->getStartX()][$word->getStartY()][] = $word;
        }

        return $this->words;
    }

    /**
     * @param $x
     * @param $y
     *
     * @return bool
     */
    public function getIsWordStart($x, $y)
    {
        $this->getWords();

        return (isset($this->wordsCoord[$x][$y]) && count($this->wordsCoord[$x][$y]) > 0);
    }

    /**
     * @param $x
     * @param $y
     *
     * @return array|null
     */
    public function getWordNumbers($x, $y)
    {
        $this->getWords();

        if (!isset($this->wordsCoord[$x][$y])) {
            return null;
        }

        $numbers = [];
        foreach ($this->wordsCoord[$x][$y] as $word) {
            $numbers[] = $word->getNumber();
        }

        return $numbers;
    }

    /**
     * @param $number
     *
     * @return Word
     */
    public function getWordByNumber($number)
    {
        foreach ($this->getWords() as $word) {
            if ($word->getNumber() == $number) {
                return $word;
            }
        }

        return null;
    }

    /**
     * @param $x
     * @param $y
     *
     * @return array|null
     */
    public function getWordCount()
    {
       return count($this->getWords());
    }

    /**
     * @param $matrix
     * @param $type
     *
     * @return Word[]
     */
    private function detectWords($matrix, $type)
    {
        /** @var Word $word */
        $words = [];

        foreach ($matrix as $x => $row) {
            ksort($row);
            $previousY = 0;
            unset($word);

            $counter = 1;
            foreach ($row as $y => $char) {
                $delta = $y - $previousY;
                if ($delta > 1 || ($y == 1 && $delta == 1)) {
                    if (isset($word) and $word->getLength() > 1) {
                        $words[] = $word;
                    }
                    $word = new Word($x, $y, $char);
                    $word->setType($type);
                } elseif ($delta == 1 && isset($word)) {
                    $word->addLetter($x, $y, $char);
                }

                if (isset($word)) {
                    $len = $word->getLength();
                }
                if (isset($word) and $word->getLength() > 1 && count($row) == $counter) {
                    $words[] = $word;
                }

                $previousY = $y;
                $counter++;
            }
        }

        return $words;
    }

    /**
     * @return Question[]
     */
    public function getQuestions()
    {
        return $this->questions;
    }

    /**
     * @return Question[]
     */
    public function getVerticalQuestions()
    {
        $words     = $this->getWords();
        $questions = $this->getQuestions();

        $selectedQuestions  = [];
        $questionsNumerated = [];

        foreach ($questions as $question) {
            $questionsNumerated[$question->getNumber()] = $question;
        }

        foreach ($words as $word) {
            if ($word->isVertical() && isset($questionsNumerated[$word->getNumber()])) {
                $selectedQuestions[] = $questionsNumerated[$word->getNumber()];
            }
        }

        return $selectedQuestions;
    }

    /**
     * @return Question[]
     */
    public function getHorizontalQuestions()
    {
        $words     = $this->getWords();
        $questions = $this->getQuestions();

        $selectedQuestions  = [];
        $questionsNumerated = [];

        foreach ($questions as $question) {
            $questionsNumerated[$question->getNumber()] = $question;
        }

        foreach ($words as $word) {
            if ($word->isHorizontal() && isset($questionsNumerated[$word->getNumber()])) {
                $selectedQuestions[] = $questionsNumerated[$word->getNumber()];
            }
        }

        return $selectedQuestions;
    }

    /**
     * @param $number
     *
     * @return string
     */
    public function getQuestionByNumber($number)
    {
        foreach ($this->getQuestions() as $question) {
            if ($question->getNumber() == $number) {
                return $question->getText();
            }
        }

        return "";
    }
}

Controller/CrosswordController.php
<?php
namespace SC\CrosswordBundle\Controller;

use SC\CrosswordBundle\Entity\Crossword;
use SC\CrosswordBundle\Entity\Letter;
use SC\CrosswordBundle\Entity\Question;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class CrosswordController extends Controller
{

    /**
     * @param Crossword $crossword
     *
     * @Template
     * @ParamConverter("crossword", class="CrosswordBundle:Crossword")
     *
     * @return array
     */
    public function pageAction(Crossword $crossword)
    {
        return [
            'crossword' => $crossword
        ];
    }

    /**
     * @param Crossword $crossword
     *
     * @ParamConverter("crossword", class="CrosswordBundle:Crossword")
     *
     * @return JsonResponse
     */
    public function getWordCoordinatesAction(Crossword $crossword)
    {
        $wordsCoordinates = [];
        foreach ($crossword->getWords() as $word) {
            $wordCoords = [];
            foreach ($word->getCoordinates() as $coord) {
                $wordCoords[] = ['x' => $coord[0], 'y' => $coord[1]];
            }
            $wordsCoordinates[$word->getNumber()] = $wordCoords;
        }

        return new JsonResponse(['success' => true, 'coordinates' => $wordsCoordinates]);
    }


    /**
     * @param Request   $request
     * @param Crossword $crossword
     *
     * @ParamConverter("crossword", class="CrosswordBundle:Crossword")
     *
     * @return Response
     */
    public function checkWordAction(Crossword $crossword, Request $request)
    {
        $question = $this->getDoctrine()
                         ->getRepository('CrosswordBundle:Question')
                         ->find($request->get('questionId'));
        if (!$question) {
            return new JsonResponse(['success' => false, 'error' => 'QUESTION_UNDEFINED']);
        }

        $word = $crossword->getWordByNumber($question->getNumber());

        if (!$word) {
            return new JsonResponse(['success' => false, 'error' => 'WORD_UNDEFINED']);
        }

        if ($word->getWord() != $request->get('word')) {
            return new JsonResponse(['success' => false, 'error' => 'WORD_INCORRECT']);
        }

        return new JsonResponse(['success' => true]);
    }
}

Resources/views/Crossword/crossword.html.twig
<script>
  $(function(){
    crossword.init();
  });
</script>

<div class="crossword-wrapper">
  <div class="crossword-wrapper-border">
    <table class="crossword" id="crossword" data-id="{{ crossword.id }}">
      {% for y in 1..crossword.height %}
        <tr>
          {% for x in 1..crossword.width %}
            <td class="letter-cell {% if not crossword.hasLetterByCoord(x, y) %} letter-cell-disabled {% endif %} coord-x-{{ x }} coord-y-{{ y }}" data-x="{{ x }}" data-y="{{ y }}">
              <div class="letter" id="letter-{{ x }}-{{ y }}">
                {% if crossword.isWordStart(x, y) %}
                  <div class="word-num">{% for number in crossword.wordNumbers(x, y) %}{{ number }}{% if not loop.last %},{% endif %}{% endfor %}</div>
                {% endif %}
                {% if crossword.hasLetterByCoord(x, y) %}
                  <input class="letter-input" id="letter-input-{{ x }}-{{ y }}" type="text" maxlength="1" data-x="{{ x }}" data-y="{{ y }}">
                {% endif %}
              </div>
            </td>
          {% endfor %}
        </tr>
      {% endfor %}
    </table>
  </div>
</div>

<div class="crossword-questions">
  <div>
    <h4>По горизонтали</h4>
    {% for question in crossword.horizontalQuestions %}
      <div class="question" data-number="{{ question.number }}"><span>{{ question.number }}</span>. {{ question.text }}</div>
    {% endfor %}

    <br>
    <h4>По вертикали</h4>
    {% for question in crossword.verticalQuestions %}
    <div class="question" data-number="{{ question.number }}"><span>{{ question.number }}</span>. {{ question.text }}</div>
    {% endfor %}
  </div>
</div>

Resources/views/Crossword/page.html.twig
{% extends ApplicationBundle ~ "::layout.html.twig" %}

{#{% block title %}{% if article.meta.title is not empty %}{{ article.meta.title }}{% else %}{{ article.title }}{% endif %}{% endblock %}#}
{#{% block meta_descr %}{% spaceless %}{% if article.meta.descr is not empty %}{{ article.meta.descr }}{% else %}{{ article.flatContent.flatContent | raw | striptags | slice(0, 200) }}{% endif %}{% endspaceless %}{% endblock %}#}
{#{% block meta_keywords %}{% if article.meta.keywords is not empty %}{{ article.meta.keywords }}{% endif %}{% endblock %}#}

{% block body %}
  <style>
    blockquote {
      padding: 5px 5px 5px 15px;
      margin: 0 0 20px;
      border-left: 5px solid #9bbfd4;
      background: #dee9ef;
      border-color: #9bbfd4;
      font-size: 19px;
      font-style: italic;
    }
  </style>

  <div class="container content">

    <div class="row-fluid">

      <div class="span9">
        {#{% set article_link %}#}
        {#{% if article.secondaryCategories[0].path is defined %}#}
        {#{{ path('islam_today_sub_category_article', {category_path:article.primaryCategory.path, sub_category_path:article.secondaryCategories[0].path, article_path:article.path}) }}#}
        {#{% else %}#}
        {#{{ path('islam_today_category_article', {category_path:article.primaryCategory.path, article_path:article.path}) }}#}
        {#{% endif %}#}
        {#{% endset %}#}
        {#<link href="http://m.islam-today.ru{{ article_link }}" rel="alternate">#}
        {#<h5><a href="{{ path('islam_today_category', {category_path:article.primaryCategory.path}) }}">{{ article.primaryCategory.title }}</a>#}
          {#{% if article.secondaryCategories[0].path is defined %}#}
          {#/ <a href="{{ path('islam_today_sub_category', {category_path:article.primaryCategory.path, sub_category_path:article.secondaryCategories[0].path}) }}">{{ article.secondaryCategories[0].title }}</a></h5>#}
        {#{% else %}#}
        {#</h5>#}
        {#{% endif %}#}

        <div class="article">

          <div class="article__header">
            <h1 class="article__header">{{ crossword.name }}</h1>
            <div class="article__indicators">
              <div class="indicator__watch indicator_gradient"><i class="icon"></i> {#{ article.getViewCnt.cnt }#}</div>
              {#{% if article.commentsCount > 0 %}#}
                {#<div class="indicator__comment indicator_gradient"><i class="icon"></i> &#123;&#35;{ article.commentsCount }&#35;&#125;</div>#}
              {#{% endif %}#}
            </div>
          </div>

          {#<div class="article__date">{{ article.publishedAt | format_date('dd MMMM Y') }} {{ article.publishedAt | date('H:i') }}</div>#}

          <div class="article__text">

            {% include "@Crossword/Crossword/crossword.html.twig" %}

          </div>

          {#{% if article.tags is not empty %}#}
            {#<div class="article__tags">#}
              {#<span class="article__tags__title">Метки:</span>#}
                        {#<span class="article__tags__items">#}
                            {#{% for tag in article.tags %}#}
                              {#{% if tag.path is not empty %}#}
                                {#<a href="{{ path('islam_today_category', {category_path:tag.path}) }}">{{ tag.title }}</a>{% if not loop.last %},{% endif %}#}
                              {#{% endif %}#}
                            {#{% endfor %}#}
                  {#</span>#}
            {#</div>#}
          {#{% endif %}#}

          {#{% render controller(ApplicationBundle~':Articles:relatedTags', {tags:article.tags}) %}#}

        </div>

        {% render controller(ApplicationBundle~':Common:socialShare') %}

        {#{% render controller(ApplicationBundle~':Articles:related', {excludeId: article.id}) %}#}

        <div class="comments" style="width:620px;">
          <div id="mc-container"></div>
          <script type="text/javascript">
            cackle_widget = window.cackle_widget || [];
            cackle_widget.push({widget: 'Comment', id: 29657});
            (function() {
              var mc = document.createElement('script');
              mc.type = 'text/javascript';
              mc.async = true;
              mc.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cackle.me/widget.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(mc, s.nextSibling);
            })();
          </script>
          <a id="mc-link" href="http://cackle.ru">Социальные комментарии <b style="color:#4FA3DA">Cackl</b><b style="color:#F65077">e</b></a>
        </div>


      </div>

      <div class="span3">

        {#{% render controller(ApplicationBundle~':Articles:popular') %}#}
        {% render(controller(ApplicationBundle ~ ":Banners:right2")) %}
        {% render(controller("SCBannersBundle:Default:getBanner", {id: 3, class: "banner-right3 sidebar_margin"})) %}
        {% render(controller(ApplicationBundle ~ ":Banners:right1")) %}
        {#<div class="panel_bordered sidebar_margin">#}
        {#<div id="hypercomments_mix"></div>#}
        {#<script type="text/javascript">#}
        {#_hcwp = window._hcwp || [];#}
        {#_hcwp.push({widget:"Mixstream", widget_id: 11350, template: "index", filter:"last",limit:5 ,default_filter:"last"});#}
        {#(function() {#}
        {#if("HC_LOAD_INIT" in window)return;#}
        {#HC_LOAD_INIT = true;#}
        {#var lang = (navigator.language || navigator.systemLanguage || navigator.userLanguage ||  "en").substr(0, 2).toLowerCase();#}
        {#var hcc = document.createElement("script"); hcc.type = "text/javascript"; hcc.async = true;#}
        {#hcc.src = ("https:" == document.location.protocol ? "https" : "http")+"://w.hypercomments.com/widget/hc/11350/"+lang+"/widget.js";#}
        {#var s = document.getElementsByTagName("script")[0];#}
        {#s.parentNode.insertBefore(hcc, s.nextSibling);#}
        {#})();#}
        {#</script>#}
        {#</div>#}

        <div class="panel_flat sidebar_margin">
          {% render(controller(ApplicationBundle ~ ":Default:services")) %}
        </div>
        {% render(controller(ApplicationBundle ~ ":Banners:holiday")) %}
        <div class="sidebar_margin">
          {#<script type="text/javascript" src="//vk.com/js/api/openapi.js?115"></script>#}

          <!-- VK Widget -->
          <div id="vk_groups1"></div>
          <script type="text/javascript">
            VK.Widgets.Group("vk_groups1", {mode: 0, width: "218", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 3963339);
          </script>
        </div>
        <div class="sidebar_margin">
          <div class="fb-like-box" data-href="https://www.facebook.com/islam.today.russia" data-width="218" data-height="400" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
        </div>

        <!-- Banner #4 -->
        <div class="iSlider" id="slider_01"></div>
        <!-- Banner #5 -->
        <div class="iSlider" id="slider_02"></div>
        <!-- Banner #6 -->
        {% render(controller(ApplicationBundle ~ ":Banners:right6")) %}


        <div class="panel_flat sidebar_margin">
          {% render(controller(ApplicationBundle ~ ':Default:photo')) %}
        </div>

        {#<div class="panel_flat sidebar_margin">#}
        {#<a href="http://www.irada.su" target="_blank"><img src="/static/banners/Banner_gif_01-13-4.gif" /></a>#}
        {#</div>#}

        <div class="panel_flat sidebar_margin">
          {% render(controller(ApplicationBundle ~ ':Default:video')) %}
        </div>


      </div>
    </div>

  </div>
{% endblock %}